### ISSUE TITLE
Can I expect this to work correctly when calling out to C libraries with ccall?

### ISSUE THREAD

**Issue by robertfeldt** [schmrlng/CPUTime.jl#2]
Thanks for CPUTime, very useful in our research to get more accurate timings on single-threaded code.

I guess the questions says it all. 

In my initial experiments it seems to be correct but have not used for any longer times so might be measurement errors... ;)

**Comment by schmrlng** [comment]
Yes, I believe so. The timer works by calling out to the OS for a measure of the current process resource usage (in the case of UNIX, [sys/resource.h](http://pubs.opengroup.org/onlinepubs/7908799/xsh/getrusage.html): "The *getrusage()* function provides measures of the resources used by the current process or its terminated and waited-for child processes."). So this should definitely work for ccall'ed code, and it may even work for stuff like [MATLAB.jl](https://github.com/JuliaLang/MATLAB.jl) which spawns a child MATLAB session, provided you close the session once you're done profiling. Of course, how to interpret results generated in this fashion would be the real question.
```
42872 schmrlng  |  `- -zsh
42897 schmrlng  |      `- julia
42944 schmrlng  |          `- /Applications/MATLAB_R2013a.app/bin/maci64/../../Contents/MacOS/MATLAB_maci64 -nosplash
```
