### ISSUE TITLE
typeassert error

### ISSUE THREAD

**Issue by rcnlee** [schmrlng/CPUTime.jl#3]
I am getting the following error when using CPUTime:

julia> using CPUTime
julia> CPUtic()
4624000
julia> CPUtoc()
ERROR: type: CPUtoq: in typeassert, expected Int32, got Int64
 in CPUtoq at C:\Users\rcnlee\.julia\v0.3\CPUTime\src\CPUTime.jl:33
 in CPUtoc at C:\Users\rcnlee\.julia\v0.3\CPUTime\src\CPUTime.jl:39

I'm on Windows 8:
julia> versioninfo()
Julia Version 0.3.3
Commit b24213b* (2014-11-23 20:19 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Any ideas?

Thanks,

Ritchie

**Comment by schmrlng** [comment]
Hopefully I've fixed it now - can you update your packages and try it again?

It's not really important, but in the interest of science what type is ```Clong``` on your Windows system? On my Mac it's ```Int64```, but I suspect it's ```Int32``` for you.
```julia
julia> Clong
Int64
```

**Comment by schmrlng** [comment]
(pending a METADATA.jl pull request going through; if ```Pkg.update()``` doesn't do anything for you right now try ```Pkg.clone("CPUTime")```)

**Comment by rcnlee** [comment]
I just tried and it works now.  Thanks Ed!
Clong is Int32 for me

Ritchie
