### ISSUE TITLE
Possibility of loosening timing?

### ISSUE THREAD

**Issue by IainNZ** [schmrlng/CPUTime.jl#4]
Hi @schmrlng,

CPUTime fails on PackageEvaluator every couple of days due to the test tolerance being too tight: http://pkg.julialang.org/?pkg=CPUTime&ver=release 

I was wondering if maybe you could loosen the testing tolerance a bit? Funny enough, it actually passed today, so I can't tell you what the tolerance needs to be, but I'll update this next time it does.

Thanks,
Iain

**Comment by schmrlng** [comment]
Sure, I've backed off on the testing tolerance a bit - to be honest I'm not too sure whether it's an issue with the timing numbers libuv is getting from the OS, or whether the sleep function just isn't that accurate. Let me know if it fails again.

Thanks,
Ed

**Comment by schmrlng** [comment]
Oh, interesting: ```sleep(1)``` can apparently be shorter than 1 second (https://travis-ci.org/schmrlng/CPUTime.jl/jobs/60613775). I'll revert the tolerance change on the high end, and add a low one as well.
