### ISSUE TITLE
Type instability in example

### ISSUE THREAD

**Issue by jlapeyre** [schmrlng/CPUTime.jl#9]
The example in the README has a type instability
```
function add_and_sleep()
    x = 0
    for i in 1:1e7
        x += i
    end
    sleep(1)
end
```
You might want to consider replacing `1e7` with `10^7`.  If you don't want to do that, you might add a warning that such a type instability should never appear in code intended to be useful.

If I remove the `sleep` call and instead return `x`, the type-stable version (`10^7`) runs more than `10^4` times faster.

**Comment by schmrlng** [comment]
Thanks -- this is a good point, especially as new users might stumble upon this package when looking for julia equivalents to functions in their previous programming languages.
